### ISSUE TITLE
Resnet fc size does not match

### ISSUE THREAD

**Issue by danieltao** [jimmyyhwu/ddsm-visual-primitives#4]
when I tried to run resnet visualization I got the following error:
![image](https://user-images.githubusercontent.com/31941194/52034637-d96f1000-24f6-11e9-815e-4d83a75bc254.png)
I did not change the code.

**Comment by jimmyyhwu** [comment]
Where is the test.py file you are running? I'm looking at line 164 of generate_unitsegments.py and it's not the same.

**Comment by danieltao** [comment]
The test.py is just generate_unitsegments.py with a different name. I added some print statements try to debug myself so the number might not be correct. The error occurs everytime I run model(input). I have also checked input shape, which is (32, 3,227,227), which looks correct.

**Comment by jimmyyhwu** [comment]
Hmm, could you attach your test.py file, and also the .../virtual_envs/ML/lib/python3.5/site-packages/torchvision/models/resnet.py file?

**Comment by danieltao** [comment]
Yes, of course.
[test.py.txt](https://github.com/jimmyyhwu/ddsm-visual-primitives/files/2818082/test.py.txt)
[resnet.py.txt](https://github.com/jimmyyhwu/ddsm-visual-primitives/files/2818083/resnet.py.txt)

**Comment by bintykhany** [comment]
> Yes, of course.
> [test.py.txt](https://github.com/jimmyyhwu/ddsm-visual-primitives/files/2818082/test.py.txt)
> [resnet.py.txt](https://github.com/jimmyyhwu/ddsm-visual-primitives/files/2818083/resnet.py.txt)

can you share full code?
